"""The in-sandbox filing reader.

These tests are the regression net for the extraction stack, and every one of
them corresponds to a defect that actually shipped and was caught by running the
tools against a real 10-K.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

SANDBOX_TOOLS = Path(__file__).resolve().parents[1] / "src" / "teamclaw" / "scenarios" / "dd_finance" / "sandbox_tools"
sys.path.insert(0, str(SANDBOX_TOOLS))

import doc  # noqa: E402


def test_normalisation_offset_map_is_exact():
    """A proportional estimate lands tens of thousands of characters away."""
    raw = "Total   net\n\n sales  391,035"
    normalised, index = doc.normalise_with_map(raw)
    assert normalised == "total net sales 391,035"
    position = normalised.find("391")
    assert raw[index[position]:].startswith("391,035")


def test_locate_returns_the_real_offset(filing_text: Path):
    hits = doc.locate(str(filing_text), "Total cost of sales")["hits"]
    assert hits
    body = filing_text.read_text(encoding="utf-8")
    assert body[hits[0]["offset"]:].lower().startswith("total cost of sales")


def test_outline_is_monotonic_and_points_at_the_body(filing_text: Path):
    """Forward-greedy locks onto the front index; the walk must run backwards."""
    items = doc.outline(str(filing_text))["items"]
    offsets = [i["offset"] for i in items]
    assert offsets == sorted(offsets)
    body = filing_text.read_text(encoding="utf-8")
    item8 = next(i for i in items if i["item"] == "Item 8")
    # The index entry sits in the first few hundred characters; the body does not.
    assert item8["offset"] > 1_000
    assert "Financial Statements" in body[item8["offset"]: item8["offset"] + 60]


def test_a_cross_reference_does_not_reorder_the_outline(filing_text: Path):
    """'See the information in Item 8 above' must not move Item 8 after Item 9."""
    items = {i["item"]: i["offset"] for i in doc.outline(str(filing_text))["items"]}
    assert items["Item 8"] < items["Item 9"]


def test_find_number_prefers_the_statement_row_over_narrative_prose(filing_text: Path):
    """'Percentage of total net sales' must not outrank 'Total net sales'."""
    best = doc.find_number(str(filing_text), "Total net sales", limit=1)["candidates"][0]
    assert best["values"][0] == 391_035
    assert best["line"].lower().startswith("total net sales")


def test_scale_headings_are_resolved_from_above_the_table(filing_text: Path):
    candidate = doc.find_number(str(filing_text), "Total assets", limit=1)["candidates"][0]
    assert candidate["scale"] == "millions"
    assert candidate["scale_factor"] == 1e6


def test_missing_scale_is_reported_not_assumed(tmp_path: Path):
    """A guessed scale is a thousand-fold error."""
    path = tmp_path / "plain.txt"
    path.write_text("Total assets 364,980\n", encoding="utf-8")
    result = doc.table_scale(str(path), 5)
    assert result["scale"] is None and result["factor"] == 1.0
    assert "do not assume" in result["note"]


def test_accounting_parentheses_survive_as_a_negative_value(filing_text: Path):
    candidate = doc.find_number(
        str(filing_text), "Payments for acquisition of property", limit=1
    )["candidates"][0]
    assert candidate["values"][0] == -9_447


@pytest.mark.parametrize(
    ("label", "expected"),
    [
        ("Total cost of sales", 210_352),
        ("Operating income", 123_216),
        ("Net income", 93_736),
        ("Total assets", 364_980),
        ("Total liabilities", 308_030),
        ("Total current assets", 152_987),
        ("Total current liabilities", 176_392),
        ("Accounts receivable", 33_410),
        ("Cash generated by operating activities", 118_254),
    ],
)
def test_l1_captions_resolve_to_the_right_figure(filing_text: Path, label: str, expected: int):
    candidates = doc.find_number(str(filing_text), label, limit=1)["candidates"]
    assert candidates, f"{label!r} not found"
    assert candidates[0]["values"][0] == expected


def test_section_extraction_is_capped_and_says_so(filing_text: Path):
    result = doc.section(str(filing_text), "Item 1", max_chars=50)
    assert result["truncated"] is True
    assert len(result["text"]) == 50


def test_grep_reports_a_bad_regex_instead_of_raising(filing_text: Path):
    result = doc.grep(str(filing_text), "(unclosed")
    assert "bad regex" in result["error"]


def test_to_text_returns_a_digest_never_the_document(tmp_path: Path):
    html = tmp_path / "f.html"
    html.write_text(
        "<html><body><p>Total net sales 391,035</p>"
        "<p>(in millions)</p></body></html>", encoding="utf-8"
    )
    info = doc.to_text(str(html))
    assert info["chars"] > 0
    assert len(info["head"]) <= 300
    assert "path" in info and Path(info["path"]).exists()
