"""Generate importable Python modules from tool specs (and from MCP schemas).

This is the concrete answer to "how does an agent use 40 tools without paying
40 JSON schemas of context". Instead of publishing schemas into the prompt, we
*compile* the tool surface into a Python package that lives on the sandbox's
``PYTHONPATH``:

    from tools import sec
    filings = sec.search_filings(cik="0000320193", form="10-K", years=3)

The agent discovers detail the way a programmer does — ``help(sec)``,
``dir(sec)``, reading the stub — which costs nothing until it is actually read.

Local tools carry their implementation inline. Bridged tools become thin
functions that post a request through the file RPC in
:mod:`tally.execution.bridge`, so the sandbox never needs network access.

MCP interop lives in :func:`specs_from_mcp`: an MCP ``tools/list`` payload maps
onto :class:`~tally.execution.registry.ToolSpec` objects, which then compile
to stubs like any other tool. That is the "MCP → Python stub" path.
"""

from __future__ import annotations

import keyword
import re
import textwrap
from pathlib import Path
from typing import Any, Iterable, Sequence

from tally.execution.registry import ToolParam, ToolRegistry, ToolSpec

JSON_TO_PY = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "list",
    "object": "dict",
    "null": "None",
}

_IDENT = re.compile(r"[^0-9a-zA-Z_]")

BRIDGE_RUNTIME = '''\
"""Sandbox-side half of the host tool bridge. Generated — do not edit.

A bridged call writes a request file into ``.rpc/`` inside the workspace and
waits for the matching response file. The workspace is the only mount shared
with the host, so this works with ``--network none``: the sandbox performs no
egress itself, and the host broker is the single audited chokepoint.
"""

from __future__ import annotations

import json
import os
import time
import uuid
from pathlib import Path

RPC_DIR = Path(os.environ.get("TALLY_RPC_DIR", "/workspace/.rpc"))
TIMEOUT_S = float(os.environ.get("TALLY_RPC_TIMEOUT", "120"))
POLL_S = 0.02


class ToolError(RuntimeError):
    """Raised when a bridged tool fails host-side."""


def call(tool: str, **kwargs: object) -> object:
    RPC_DIR.mkdir(parents=True, exist_ok=True)
    call_id = uuid.uuid4().hex[:12]
    req = RPC_DIR / f"{call_id}.req.json"
    res = RPC_DIR / f"{call_id}.res.json"

    tmp = req.with_suffix(".tmp")
    tmp.write_text(json.dumps({"id": call_id, "tool": tool, "kwargs": kwargs}), encoding="utf-8")
    os.replace(tmp, req)  # atomic: the broker never sees a partial request

    deadline = time.time() + TIMEOUT_S
    while time.time() < deadline:
        if res.exists():
            payload = json.loads(res.read_text(encoding="utf-8"))
            # Consume the response. Leaving it behind would accumulate RPC
            # plumbing in the workspace and pollute the digest the agent reads.
            try:
                res.unlink()
            except OSError:
                pass
            if payload.get("error"):
                raise ToolError(f"{tool}: {payload['error']}")
            return payload.get("result")
        time.sleep(POLL_S)
    raise ToolError(f"{tool}: host bridge did not respond within {TIMEOUT_S}s")
'''


def safe_ident(name: str) -> str:
    ident = _IDENT.sub("_", name)
    if not ident or ident[0].isdigit():
        ident = f"_{ident}"
    if keyword.iskeyword(ident):
        ident = f"{ident}_"
    return ident


def render_function(spec: ToolSpec) -> str:
    params = ", ".join(p.render() for p in spec.params)
    doc = textwrap.indent(f'"""{spec.docstring()}\n"""', "    ")
    if spec.local_source:
        body = textwrap.indent(textwrap.dedent(spec.local_source).strip(), "    ")
    else:
        kwargs = ", ".join(f"{p.name}={p.name}" for p in spec.params)
        body = textwrap.indent(
            f"return _bridge.call({spec.name!r}{', ' + kwargs if kwargs else ''})", "    "
        )
    return f"def {spec.func}({params}) -> {spec.returns}:\n{doc}\n{body}\n"


def render_module(module: str, specs: Sequence[ToolSpec]) -> str:
    needs_bridge = any(s.bridged for s in specs)
    header = [
        f'"""Tool module `{module}` — generated by tally.execution.stubgen.',
        "",
        "Do not edit: regenerated from the tool registry on every run so the",
        "sandbox surface and the host registry cannot drift apart.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    if needs_bridge:
        header += ["from tools import _bridge", ""]
    # Local implementations may need these; unused imports are harmless in a stub.
    header += ["import json", "import math", "from pathlib import Path", "", ""]
    functions = [render_function(s) for s in sorted(specs, key=lambda s: s.func)]
    exports = ", ".join(repr(s.func) for s in sorted(specs, key=lambda s: s.func))
    footer = [f"__all__ = [{exports}]", ""]
    return "\n".join(header) + "\n\n".join(functions) + "\n\n" + "\n".join(footer)


def write_package(tools_dir: Path | str, registry: ToolRegistry) -> list[str]:
    """Materialise ``tools/`` for mounting into the sandbox. Returns module names."""
    root = Path(tools_dir) / "tools"
    root.mkdir(parents=True, exist_ok=True)

    (root / "_bridge.py").write_text(BRIDGE_RUNTIME, encoding="utf-8")

    modules = registry.modules()
    for module in modules:
        attached = registry.module_sources.get(module)
        source = attached if attached is not None else render_module(
            module, registry.by_module(module)
        )
        (root / f"{module}.py").write_text(source, encoding="utf-8")

    init = [
        '"""Generated tool package. Import the module you need:',
        "",
        *[f"    from tools import {m}" for m in modules],
        '"""',
        "",
        f"__all__ = {modules!r}",
        "",
    ]
    (root / "__init__.py").write_text("\n".join(init), encoding="utf-8")
    return modules


# -- MCP interop -----------------------------------------------------------
def params_from_json_schema(schema: dict[str, Any]) -> list[ToolParam]:
    """Map an MCP ``inputSchema`` onto Python parameters.

    Required parameters come first and carry no default, because Python forbids a
    non-default parameter after a defaulted one — an ordering detail that quietly
    produces a ``SyntaxError`` in the generated module if ignored.
    """
    props: dict[str, Any] = (schema or {}).get("properties") or {}
    required = set((schema or {}).get("required") or [])

    def annotate(spec: dict[str, Any]) -> str:
        raw = spec.get("type")
        if isinstance(raw, list):
            raw = next((t for t in raw if t != "null"), "string")
        return JSON_TO_PY.get(str(raw), "object")

    ordered = sorted(props.items(), key=lambda kv: (kv[0] not in required, kv[0]))
    out: list[ToolParam] = []
    for name, spec in ordered:
        ident = safe_ident(name)
        out.append(
            ToolParam(
                name=ident,
                annotation=annotate(spec),
                default=None if name in required else "None",
                doc=str(spec.get("description", "")).strip(),
            )
        )
    return out


def specs_from_mcp(
    tools: Iterable[dict[str, Any]],
    *,
    module: str,
    requires_network: bool = True,
) -> list[ToolSpec]:
    """Convert an MCP ``tools/list`` result into registry specs.

    The MCP tool name is preserved on the wire (the bridge dispatches on
    ``module.func``), while the Python identifier is sanitised — MCP names
    routinely contain hyphens and dots that are not valid Python.
    """
    specs: list[ToolSpec] = []
    for tool in tools:
        raw_name = str(tool.get("name") or "").strip()
        if not raw_name:
            continue
        description = str(tool.get("description") or "").strip()
        summary = description.splitlines()[0][:160] if description else raw_name
        detail = "\n".join(description.splitlines()[1:]).strip()
        specs.append(
            ToolSpec(
                module=module,
                func=safe_ident(raw_name.split(".")[-1].split("/")[-1]),
                summary=summary,
                params=params_from_json_schema(tool.get("inputSchema") or {}),
                returns="object",
                detail=(detail + f"\n\n(MCP tool: {raw_name})").strip(),
                requires_network=requires_network,
                tags=("mcp", module),
            )
        )
    return specs
