"""Measure the context cost of each ablation arm, with no model calls.

Why this is a real measurement despite there being no model
-----------------------------------------------------------
An arm differs from `full` in two separable ways: how much context it spends and
how accurate it is. The second needs a model. The first does not — prompt
construction is deterministic given the same objective, workspace and history —
so the token effect of removing the ledger or the tool retrieval can be measured
now and reported on its own. Accuracy is deliberately absent.

Why the window is swept
-----------------------
A first version of this script ran one trajectory at a 32k window and found the
arms within 3% of each other, which is true and useless: peak utilisation was 8%,
so the ledger had no scarcity to allocate and nothing was ever evicted. The
mechanisms only engage under pressure, and reporting a single roomy configuration
would have measured a regime where they are inert.

So the same trajectory runs across a window sweep. What the sweep shows is the
*crossover*: the point at which a budgeted allocator starts to differ from naive
truncation, and by how much. That is the more useful claim, and it is one a
single data point cannot support.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from teamclaw.config import settings
from teamclaw.context.slots import SlotName
from teamclaw.evaluation.runner import ARMS, ArmConfig
from teamclaw.execution.workspace import Workspace
from teamclaw.models.providers.fake import ScriptedProvider
from teamclaw.models.router import Registry, Router
from teamclaw.observability.trace import Tracer, new_run_id
from teamclaw.orchestration.agent import Agent
from teamclaw.scenarios.dd_finance.sec_client import SecClient
from teamclaw.scenarios.dd_finance.spec import build_spec, build_tools, l1_objective

# A trajectory that touches the document, persists artefacts and accumulates
# history — the shape a real L1 extraction has, without needing a model to
# produce it.
# Twelve fields located three candidates at a time, which is what a real L1
# extraction prints: enough observation volume that history actually accumulates.
LABELS = (
    ("Total net sales", "Total revenues"),
    ("Total cost of sales", "Cost of revenue"),
    ("Operating income", "Income from operations"),
    ("Net income", "Net earnings"),
    ("Total assets", ""),
    ("Total liabilities", ""),
    ("Total shareholders' equity", "Total stockholders' equity"),
    ("Total current assets", ""),
    ("Total current liabilities", ""),
    ("Accounts receivable", "Receivables, net"),
    ("Cash generated by operating activities", "Net cash provided by operating activities"),
    ("Payments for acquisition of property, plant and equipment", "Capital expenditures"),
)


def _synonym_step(labels: tuple[tuple[str, str], ...]) -> str:
    """Retry the alternative caption for each field — what filer variance forces."""
    names = ", ".join(repr(b) for _, b in labels if b)
    if not names:
        names = repr(labels[0][0])
    return (
        "THOUGHT: the primary captions missed some fields, try the synonyms\n```python\n"
        "from tools import doc\n"
        "import glob\n"
        "txt = glob.glob('filings/*.txt')[0]\n"
        f"for label in ({names},):\n"
        "    r = doc.find_number(txt, label, limit=2)\n"
        "    print(label, '->', r['count'], 'candidates')\n"
        "    for c in r['candidates']:\n"
        "        print('   ', c['page_estimate'], c['item'], c['scale'],\n"
        "              c['values'][:4], '|', c['line'][:80])\n```"
    )


def _lookup_step(labels: tuple[tuple[str, str], ...]) -> str:
    names = ", ".join(repr(a) for a, _ in labels)
    return (
        "THOUGHT: locate these figures and print the candidates\n```python\n"
        "from tools import doc\n"
        "import glob\n"
        "txt = glob.glob('filings/*.txt')[0]\n"
        f"for label in ({names},):\n"
        "    r = doc.find_number(txt, label, limit=3)\n"
        "    for c in r['candidates']:\n"
        "        print(label, '|', c['page_estimate'], c['item'], c['scale'],\n"
        "              c['values'][:4], '|', c['line'][:90])\n```"
    )


# A realistic length. A real L1 extraction is not four lookups: captions differ
# between filers, so the agent tries synonyms, re-checks scales, and revisits
# fields it abstained on. Sixteen steps is the shape those runs actually have,
# and history accumulating across them is what makes the budget bind at all.
TRAJECTORY = [
    "THOUGHT: download the filing\n```python\n"
    "from tools import sec, doc\n"
    "meta = sec.download_filing(ticker='AAPL', fiscal_year=2024)\n"
    "info = doc.to_text(meta['path'])\n"
    "print({k: info[k] for k in ('chars','estimated_pages','document_scale_hint')})\n"
    "print(doc.outline(info['path'])['items'])\n```",
    # Primary captions, two fields at a time.
    *[_lookup_step(LABELS[i:i + 2]) for i in range(0, len(LABELS), 2)],
    # Synonym retries, which is where a real run spends much of its budget.
    *[_synonym_step(LABELS[i:i + 3]) for i in range(0, len(LABELS), 3)],
    "THOUGHT: confirm the scales I read\n```python\n"
    "from tools import doc\n"
    "import glob\n"
    "txt = glob.glob('filings/*.txt')[0]\n"
    "print(doc.grep(txt, r'in (thousands|millions|billions)', limit=12))\n```",
    "THOUGHT: persist what we have\n```python\n"
    "from tools import doc\n"
    "doc.save_json({'revenue': 391035000000}, 'l1.json')\n"
    "print('saved')\n```",
    "DONE\nExtracted the available L1 fields.",
]

# Swept low enough that the budget actually binds. The upper end is included to
# show the mechanisms going inert, which is the point of the sweep.
WINDOW_SWEEP = (6_000, 8_000, 12_000, 16_000, 32_000)


def measure(arm: ArmConfig, root: Path, window: int) -> dict:
    cfg = settings()
    run_id = new_run_id()
    run_dir = root / "runs" / f"{arm.name}_{window}_{run_id}"
    tracer = Tracer(run_id, run_dir)
    workspace = Workspace.create(root / "ws", f"{arm.name}_{window}")
    workspace.clear()

    provider = ScriptedProvider(TRAJECTORY, name="scripted", loop_last=True)
    registry = Registry(providers={"scripted": provider})
    for purpose in list(registry.policy):
        registry.policy[purpose] = ("scripted",)
    router = Router(registry, tracer=tracer, scenario="dd_finance")

    tools = build_tools(SecClient(cfg=cfg), workspace)
    # A fixed 2048-token output reservation would consume a third of a 6k window
    # before any slot bids, so the reservation scales with the window.
    spec = build_spec(tools=tools, window=window, max_steps=len(TRAJECTORY) + 2,
                      max_output=min(2_048, max(512, window // 8)),
                      prefer_docker=False)
    spec.policies = arm.policies()
    if not arm.tool_retrieval:
        spec.tool_k = len(tools)
    if not arm.skills:
        spec.skill_k = 0
    if not arm.compaction:
        spec.compaction_threshold = 10.0

    agent = Agent(spec, router=router, workspace=workspace, tracer=tracer, run_dir=run_dir)
    if not arm.memory:
        agent.spec.memory_k = 0

    run = agent.run(l1_objective("AAPL", 2024))
    tracer.close()

    per_step = [s.ledger for s in run.steps]
    slot_totals: dict[str, int] = {}
    for record in per_step:
        for fill in record.fills:
            slot_totals[fill.policy.name.value] = (
                slot_totals.get(fill.policy.name.value, 0) + fill.used
            )
    return {
        "arm": arm.name,
        "window": window,
        "description": arm.description,
        "steps": run.step_count,
        "finished": run.finished,
        "prompt_tokens_total": sum(r.used for r in per_step),
        "prompt_tokens_mean_per_step": round(
            sum(r.used for r in per_step) / len(per_step), 1) if per_step else 0,
        "prompt_tokens_peak_step": max((r.used for r in per_step), default=0),
        "peak_utilisation": round(max((r.utilisation for r in per_step), default=0.0), 4),
        "evicted_tokens_total": sum(r.evicted_tokens for r in per_step),
        "slot_tokens": dict(sorted(slot_totals.items())),
        "compactions": agent.compactor.stats().get("compactions", 0),
    }


def main() -> int:
    root = settings().paths.runs / "arm_context_cost"
    root.mkdir(parents=True, exist_ok=True)
    arms = [a for a in ARMS if not a.allow_paid]

    rows: list[dict] = []
    for window in WINDOW_SWEEP:
        for arm in arms:
            print(f"measuring {arm.name} @ {window} ...", flush=True)
            rows.append(measure(arm, root, window))

    by_window: dict[int, dict[str, dict]] = {}
    for row in rows:
        by_window.setdefault(row["window"], {})[row["arm"]] = row
    for window, arms_at_window in by_window.items():
        base = arms_at_window["full"]["prompt_tokens_mean_per_step"] or 1
        for row in arms_at_window.values():
            row["delta_vs_full_pct"] = round(
                100.0 * (row["prompt_tokens_mean_per_step"] - base) / base, 1
            )

    report = {
        "measurement": "context cost per ablation arm, across a window sweep",
        "model_calls": "scripted — the identical trajectory in every arm",
        "note": ("Accuracy is deliberately absent: it requires a real model. Only "
                 "the deterministic half of an arm's effect is measured here. The "
                 "sweep exists because at a roomy window every arm looks alike — "
                 "the mechanisms only engage once the budget binds."),
        "windows": list(WINDOW_SWEEP),
        "arms": rows,
    }
    out = Path("results") / "arm_context_cost.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=1), encoding="utf-8")

    for window in WINDOW_SWEEP:
        arms_at_window = by_window[window]
        util = arms_at_window["full"]["peak_utilisation"]
        print(f"\n=== window {window:,} — full arm peak utilisation {util:.0%} ===")
        print(f"{'arm':<22} {'mean tok/step':>13} {'peak':>7} {'evicted':>8} "
              f"{'compact':>8} {'vs full':>9}")
        print("-" * 72)
        for name in ("full", "minus-ledger", "minus-tool-retrieval", "minus-compaction",
                     "minus-memory", "minus-skills"):
            row = arms_at_window.get(name)
            if row is None:
                continue
            print(f"{name:<22} {row['prompt_tokens_mean_per_step']:>13} "
                  f"{row['prompt_tokens_peak_step']:>7} {row['evicted_tokens_total']:>8} "
                  f"{row['compactions']:>8} {row['delta_vs_full_pct']:>+8.1f}%")
    print(f"\n-> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
