"""Phase-0 floor arm: extract L1 with the tools alone, zero model calls.

Why this arm exists
-------------------
"The scaffold contributed X points" needs a floor to measure from. This is that
floor: the document tools driven by a fixed caption table and no intelligence at
all. Whatever a model adds is measured against this, not against zero.

It is also the cheapest possible regression test for the extraction stack — it
runs offline against the SEC cache, needs no credentials, and its score moves the
moment `doc.find_number`, the offset map, or the scale detection regresses.
"""

from __future__ import annotations

import json
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src" / "tally" / "scenarios" / "dd_finance" / "sandbox_tools"))

import doc  # noqa: E402

from tally.config import settings  # noqa: E402
from tally.evaluation.metrics import (  # noqa: E402
    abstention_accuracy,
    aggregate,
    citation_verifiability,
    numeric_accuracy,
)
from tally.execution.workspace import Workspace  # noqa: E402
from tally.scenarios.dd_finance.groundtruth import load_dataset  # noqa: E402
from tally.scenarios.dd_finance.sec_client import SecClient  # noqa: E402
from tally.scenarios.dd_finance.spec import SecHandlers  # noqa: E402

# Caption synonyms per L1 field, in preference order. Deliberately hand-written:
# the point of this arm is to show what a fixed rule set achieves so that a
# model's contribution is legible.
CAPTIONS: dict[str, tuple[str, ...]] = {
    "revenue": ("Total net sales", "Total revenues", "Total revenue", "Net revenues",
                "Revenues", "Total net revenues"),
    "cost_of_revenue": ("Total cost of sales", "Cost of sales", "Cost of revenue",
                        "Total cost of revenues", "Cost of goods sold"),
    "operating_income": ("Operating income", "Income from operations",
                         "Total operating income", "Operating income (loss)"),
    "net_income": ("Net income", "Net income (loss)", "Net earnings",
                   "Net income attributable"),
    "total_assets": ("Total assets",),
    "total_liabilities": ("Total liabilities",),
    "total_equity": ("Total shareholders’ equity", "Total shareholders' equity",
                     "Total stockholders’ equity", "Total stockholders' equity",
                     "Total equity"),
    "current_assets": ("Total current assets",),
    "current_liabilities": ("Total current liabilities",),
    "accounts_receivable": ("Accounts receivable", "Accounts receivable, net",
                            "Receivables, net", "Trade receivables"),
    "cash_from_operations": ("Cash generated by operating activities",
                             "Net cash provided by operating activities",
                             "Cash provided by operating activities",
                             "Net cash from operating activities"),
    "capex": ("Payments for acquisition of property, plant and equipment",
              "Purchases of property and equipment",
              "Capital expenditures",
              "Additions to property, plant and equipment"),
}
MIN_ROW_SCORE = 8.0


def extract(text_path: str, scale_hint: float) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for key, captions in CAPTIONS.items():
        best = None
        for caption in captions:
            result = doc.find_number(text_path, caption, limit=1)
            if not result["candidates"]:
                continue
            cand = result["candidates"][0]
            if cand["looks_like_statement_row"] < MIN_ROW_SCORE:
                continue
            values = [v for v in cand.get("values") or [] if v is not None]
            if not values:
                continue
            best = (caption, cand, values[0])
            break
        if best is None:
            out[key] = {"value": None, "reason": "not_disclosed"}
            continue
        caption, cand, raw = best
        factor = cand["scale_factor"] or scale_hint or 1.0
        out[key] = {
            "value": abs(raw) * factor if key in {"capex", "cost_of_revenue"} else raw * factor,
            "unit": "USD",
            "page": cand["page_estimate"],
            "quote": cand["quote"][:180],
            "caption_used": caption,
            "scale": cand["scale"],
        }
    return out


def main(limit: int | None = None) -> int:
    cfg = settings()
    cases = [c for c in load_dataset(cfg.paths.datasets / "dd_finance_groundtruth.jsonl")
             if not c.held_out]
    if limit:
        cases = cases[:limit]
    client = SecClient(cfg=cfg)
    ws_root = cfg.paths.workspaces / "deterministic_baseline"

    numeric: list = []
    citations: list = []
    abstentions: list = []
    per_case: list[dict] = []
    failures = 0

    for n, case in enumerate(cases, 1):
        ws = Workspace.create(ws_root, case.case_id)
        try:
            meta = SecHandlers(client=client, workspace=ws).download_filing(
                case.ticker, case.fiscal_year
            )
            info = doc.to_text(str(ws.resolve(meta["path"])))
            hint = {"thousands": 1e3, "millions": 1e6, "billions": 1e9}.get(
                info.get("document_scale_hint") or "", 1.0
            )
            predicted = extract(info["path"], hint)
            source = Path(info["path"]).read_text(encoding="utf-8", errors="replace")
        except Exception as exc:  # noqa: BLE001
            failures += 1
            print(f"[{n:>3}/{len(cases)}] {case.case_id:<14} FAILED {type(exc).__name__}: {exc}",
                  flush=True)
            continue

        bands = numeric_accuracy(predicted, case.l1)
        numeric.append(bands["strict"])
        cit = citation_verifiability(predicted, source)
        citations.append(cit)
        abst = abstention_accuracy(predicted, case.l1, absent_keys=case.l1_absence_trusted)
        abstentions.append(abst)
        per_case.append({
            "case": case.case_id, "sector": case.sector,
            "numeric_strict": bands["strict"].rate,
            "citation": cit.rate, "abstention": abst.rate,
        })
        print(f"[{n:>3}/{len(cases)}] {case.case_id:<14} {case.sector:<11} "
              f"numeric@strict={bands['strict'].rate:.2f} cite={cit.rate:.2f} "
              f"abstain={abst.rate:.2f}", flush=True)

    report = {
        "arm": "deterministic-tools-only",
        "model_calls": 0,
        "cases_attempted": len(cases),
        "cases_scored": len(per_case),
        "cases_failed": failures,
        "numeric_accuracy_strict": aggregate(numeric).to_json(),
        "citation_verifiability": aggregate(citations).to_json(),
        "abstention_accuracy": aggregate(abstentions).to_json(),
        "per_case": per_case,
        "note": ("Zero model calls. This is the floor a language model must beat, "
                 "and the cheapest regression test for the extraction stack."),
    }
    out = cfg.paths.runs / "deterministic_baseline.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=1, default=str), encoding="utf-8")

    print("\n=== deterministic floor (0 model calls) ===")
    for key in ("numeric_accuracy_strict", "citation_verifiability", "abstention_accuracy"):
        r = report[key]
        print(f"  {key:<26} {r['rate']:.4f}  ({r['correct']}/{r['total']})")
    print(f"  cases scored: {len(per_case)}  failed: {failures}")
    print(f"  -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(int(sys.argv[1]) if len(sys.argv) > 1 else None))
